### ISSUE TITLE
no server side? 

### ISSUE THREAD

**Issue by Legendmanj** [Maulve/maulves-scythes#5]
can this be used on fabric servers? if yes please notify

if not please mind implementing the feature, as it would actually be better and make the mod more good that before ig

**Comment by Maulve** [comment]
(sorry for the very late reply, i didn't get any notification)

I don't know, I haven't tested it yet.
If it doesn't already work, I would definitely implement it if I knew how to. But I'll see then.

**Comment by Maulve** [comment]
Update: I tested it and figured out that it doesn't work.

I add it in a future update, either 1.2 or 1.3.

**Comment by Maulve** [comment]
This mod can now be run in multiplayer as of [This Commit](https://github.com/Maulve/maulves-scythes/commit/dd5c9a3b6278c86a34323acdd61543fe7db020e6).
Update 1.2.0 will feature this.
