### ISSUE TITLE
1.21?

### ISSUE THREAD

**Issue by Legendmanj** [Maulve/maulves-scythes#6]
requesting the 1.21 update to be implemented

if the mod can be used on 1.21 with the 1.20.6 version, let me know (:

Thankyou

**Comment by Maulve** [comment]
(sorry for the very late reply, i didn't get any notification)

I haven't tested with 1.21 compatibility, however I will implement that whenever I have some spare time.

**Comment by Maulve** [comment]
1.21 support is now in version 1.2.1
